name: 'jira-version'
description: 'Pulls the latest unreleased version for a given project from Jira'
author: 'Jim Yang'
inputs:
  subdomain:
    required: true
    description: '{subdomain}.atlassian.com'
  project:
    required: true
    description: Jira project id (i.e. ticket prefix)
  email:
    required: true
    description: Email address associated with api token
  api-token:
    required: true
    description: Jira API token
runs:
  using: 'node12'
  main: 'dist/index.js'
